SCREEN_WIDTH    = 800
SCREEN_HEIGHT   = 600

PADDLE_WIDTH    = 100
PADDLE_HEIGHT   = 20
PADDLE_Y        = -SCREEN_HEIGHT // 2 + 50
PADDLE_SPEED    = 10

BALL_RADIUS     = 10

BRICK_ROWS      = 8
BRICK_COLS      = 14
BRICK_WIDTH     = SCREEN_WIDTH // BRICK_COLS - 5
BRICK_HEIGHT    = 25
BRICK_START_Y   = SCREEN_HEIGHT // 2 - 100

COLORS_AND_POINTS = [("yellow", 1), ("green", 3), ("orange", 5), ("red", 7)]

FPS_DELAY       = 0.01 # ~60 FPS
AUTO_LAUNCH_SEC = 2.0